import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const OWNER = 'devfellowship'
const REPO = 'dfl-slide-templates'
const BASE_BRANCH = 'main'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers':
    'authorization, x-client-info, apikey, content-type',
}

interface PublishPayload {
  type: 'template' | 'theme'
  id: string
  description: string
  files: Array<{ path: string; content: string }>
  registryEntry?: { id: string; version: string; category: string }
}

async function githubApi(path: string, options: RequestInit = {}) {
  const token = Deno.env.get('GITHUB_ORG_ADMIN_PAT')
  if (!token) throw new Error('GITHUB_ORG_ADMIN_PAT not configured')

  const res = await fetch(
    `https://api.github.com/repos/${OWNER}/${REPO}${path}`,
    {
      ...options,
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
        'Content-Type': 'application/json',
        ...(options.headers as Record<string, string>),
      },
    },
  )

  if (!res.ok) {
    const body = await res.text()
    throw new Error(`GitHub API ${res.status}: ${body}`)
  }

  return res.json()
}

function jsonResponse(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  })
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  try {
    const authHeader = req.headers.get('Authorization')
    if (!authHeader) {
      return jsonResponse({ error: 'Missing authorization' }, 401)
    }

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
    )

    const jwt = authHeader.replace('Bearer ', '')
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser(jwt)
    if (authError || !user) {
      return jsonResponse({ error: 'Unauthorized' }, 401)
    }

    const payload: PublishPayload = await req.json()
    const { type, id, description, files, registryEntry } = payload

    if (!type || !id || !description || !files?.length) {
      return jsonResponse({ error: 'Missing required fields' }, 400)
    }

    const allFiles = [...files]

    if (registryEntry) {
      const registryRaw = await githubApi(
        `/contents/registry.json?ref=${BASE_BRANCH}`,
      )
      const currentRegistry = JSON.parse(atob(registryRaw.content))
      const idx = currentRegistry.templates.findIndex(
        (t: { id: string }) => t.id === registryEntry.id,
      )
      if (idx >= 0) {
        currentRegistry.templates[idx] = registryEntry
      } else {
        currentRegistry.templates.push(registryEntry)
      }
      allFiles.push({
        path: 'registry.json',
        content: JSON.stringify(currentRegistry, null, 2) + '\n',
      })
    }

    // 1. Get main branch ref
    const ref = await githubApi(`/git/ref/heads/${BASE_BRANCH}`)
    const baseSha: string = ref.object.sha

    // 2. Get base commit tree
    const baseCommit = await githubApi(`/git/commits/${baseSha}`)
    const baseTreeSha: string = baseCommit.tree.sha

    // 3. Create new tree with file changes
    const newTree = await githubApi('/git/trees', {
      method: 'POST',
      body: JSON.stringify({
        base_tree: baseTreeSha,
        tree: allFiles.map((f) => ({
          path: f.path,
          mode: '100644',
          type: 'blob',
          content: f.content,
        })),
      }),
    })

    // 4. Create commit
    const timestamp = Date.now()
    const branchName = `template-studio/${type}-${id}-${timestamp}`
    const commitMessage =
      type === 'template'
        ? `feat(templates): ${description}`
        : `feat(themes): ${description}`

    const newCommit = await githubApi('/git/commits', {
      method: 'POST',
      body: JSON.stringify({
        message: commitMessage,
        tree: newTree.sha,
        parents: [baseSha],
      }),
    })

    // 5. Create branch
    await githubApi('/git/refs', {
      method: 'POST',
      body: JSON.stringify({
        ref: `refs/heads/${branchName}`,
        sha: newCommit.sha,
      }),
    })

    // 6. Open PR
    const prBody = [
      '## Template Studio Publish',
      '',
      `**Type:** ${type}`,
      `**ID:** \`${id}\``,
      `**Author:** ${user.email || user.id}`,
      '',
      '### Changed files',
      '',
      ...allFiles.map((f) => `- \`${f.path}\``),
      '',
      '---',
      '_This PR was automatically generated by Template Studio._',
    ].join('\n')

    const pr = await githubApi('/pulls', {
      method: 'POST',
      body: JSON.stringify({
        title: commitMessage,
        body: prBody,
        head: branchName,
        base: BASE_BRANCH,
      }),
    })

    return jsonResponse({
      prUrl: pr.html_url,
      prNumber: pr.number,
      branch: branchName,
    })
  } catch (err) {
    console.error('Publish error:', err)
    return jsonResponse(
      { error: err instanceof Error ? err.message : 'Internal error' },
      500,
    )
  }
})
